server:
  port: 8080

spring:
  application:
    name: players-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

aws:
  xray:
    enabled: true
    daemon-address: "${AWS_XRAY_DAEMON_ADDRESS:127.0.0.1:2000}"
    name: "${XRAY_SERVICE_NAME:todo: (service name as it should appear in X-Ray)}"
    sampling-strategy: "${XRAY_SAMPLING_STRATEGY:default}"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  aws:
    region: ${AWS_REGION:us-east-1}
    dynamodb-endpoint: ${DYNAMODB_ENDPOINT:}
    s3-endpoint: ${S3_ENDPOINT:} # optional local override
    eventbridge-endpoint: ${EVENTBRIDGE_ENDPOINT:} # optional local override
  reports:
    table-name: ${REPORTS_TABLE_NAME:vsm-main}
  s3:
    reportsBucket: "${REPORTS_BUCKET_NAME:Todo: S3 reports bucket name}"
    keyPrefix: "${REPORTS_KEY_PREFIX:Todo: Optional prefix like 'reports/'}"
  kms:
    keyArn: "${REPORTS_KMS_KEY_ARN:Todo: KMS key ARN for SSE-KMS}"
  events:
    busName: "${EVENTBUS_NAME:Todo: EventBridge bus name}"
    source: "${EVENT_SOURCE:Todo: Event source string (e.g., 'com.vsm.reports')}"
    detailType:
      reportCreated: "${EVENT_DETAIL_TYPE_REPORT_CREATED:Todo: Event detail-type (e.g., 'report.created')}"
