server:
  port: 8080

spring:
  application:
    name: players-api

  # Default profile: "dev" (auth enabled). Set issuer via env var COGNITO_ISSUER_URI
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  aws:
    region: ${AWS_REGION:us-east-1}
    dynamodb-endpoint: ${DYNAMODB_ENDPOINT:}
  reports:
    table-name: ${REPORTS_TABLE_NAME:vsm-main}
  s3:
    reportsBucket: "Todo: S3 reports bucket name"
    keyPrefix: "Todo: Optional prefix like 'reports/'"
  kms:
    keyArn: "Todo: KMS key ARN for SSE-KMS"
  events:
    busName: "Todo: EventBridge bus name"
    source: "Todo: Event source string (e.g., 'com.vsm.reports')"
    detailType:
      reportCreated: "Todo: Event detail-type (e.g., 'report.created')"
