server:
  port: 8080

spring:
  application:
    name: players-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  aws:
    region: ${AWS_REGION:us-east-1}
    dynamodb-endpoint: ${DYNAMODB_ENDPOINT:}
    s3-endpoint: ${S3_ENDPOINT:} # optional local override
    eventbridge-endpoint: ${EVENTBRIDGE_ENDPOINT:} # optional local override
  reports:
    table-name: ${REPORTS_TABLE_NAME:vsm-main}
  s3:
    reportsBucket: "${REPORTS_BUCKET_NAME:Todo: S3 reports bucket name}"
    keyPrefix: "${REPORTS_KEY_PREFIX:Todo: Optional prefix like 'reports/'}"
    rawUploadsBucket: "${RAW_UPLOADS_BUCKET_NAME:Todo: Raw uploads bucket name}"
    rawUploadsPrefix: "${RAW_UPLOADS_KEY_PREFIX:uploads/}"
    rawUploadExpirySeconds: ${RAW_UPLOADS_EXPIRY_SECONDS:900}
  kms:
    keyArn: "${REPORTS_KMS_KEY_ARN:Todo: KMS key ARN for SSE-KMS}"
  events:
    busName: "${EVENTBUS_NAME:Todo: EventBridge bus name}"
    source: "${EVENT_SOURCE:Todo: Event source string (e.g., 'com.vsm.reports')}"
    detailType:
      reportCreated: "${EVENT_DETAIL_TYPE_REPORT_CREATED:Todo: Event detail-type (e.g., 'report.created')}"
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:}
  security:
    max-payload-bytes: ${MAX_PAYLOAD_BYTES:1048576}
