# Local profile: disable auth (see SecurityConfig @Profile("local"))
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""

app:
  aws:
    dynamodb-endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}
  soap:
    endpoint-url: ""
    soap-action: ""
    connect-timeout: 2s
    read-timeout: 5s
