server:
  port: 8080

spring:
  application:
    name: players-api

  # Default profile: "dev" (auth enabled). Set issuer via env var COGNITO_ISSUER_URI
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
