name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/players-api
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build & Test (verify)
        run: ./mvnw -B verify

  build-angular:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint
      - run: npm run format
      - run: npm run test

