name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "Configure CI workflow"

  build-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/players-api
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Build & Test
        run: ./mvnw -q -e verify
